print("#program menghitung luas dan keliling lingkaran")
r = input('masukkan r dari lingkaran')
d = input('masukkan d dari lingkaran')
luas = int(22/7)*int(r)*int(r)
keliling = int(22/7)*int(d)
print("luas dari lingkaran ? " ,luas)
print("keliling dari lingkaran ? " ,keliling)
